---
groups:
  - name: global-net-aws-bats
    jobs:
      - build-candidate
      - bats-ubuntu

jobs:
  - name: build-candidate
    serial: true
    plan:
      - aggregate:
        - {trigger: false, get: bosh-cpi-release, resource: bosh-cpi-release-in}
        - {trigger: false, get: version-semver, params: {bump: patch}}

      - put: version-semver
        params: {file: version-semver/number}

      - task: build
        file: bosh-cpi-release/ci/tasks/build-candidate.yml

      - put: bosh-cpi-dev-artifacts
        params: {from: build/out/.*\.tgz}

  - name: bats-ubuntu
    serial: true
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate],  get: bosh-cpi-dev-artifacts}
        - {trigger: false,                             get: stemcell, resource: aws-ubuntu-hvm-stemcell}
        - {trigger: false, passed: [build-candidate],  get: bosh-cpi-release, resource: bosh-cpi-release-in}
        - {trigger: false,                             get: bats}
        - {trigger: false,                             get: bosh-init}
        - {trigger: false, passed: [build-candidate],  get: version-semver}
#        - {trigger: false,                             get: bosh-release}

      - task: create-dev-release
        file: bosh-src/ci/pipelines/global-net-bats/create-dev-release.yml

      - task: setup-director
        file: bosh-src/ci/pipelines/global-net-bats/setup-director.yml
        config:
          params:
            base_os:                    Ubuntu
            aws_access_key_id:          {{aws_access_key__primary}}
            aws_secret_access_key:      {{aws_secret_key__primary}}
            region_name:                {{aws_region__primary}}
            private_key_data:           {{bosh_private_key}}
            stack_name:                 primary

#      - task: run-bats
#        file: bosh-cpi-release/ci/tasks/run-bats.yml
#        config:
#          params:
#            base_os:                    Ubuntu
#            aws_access_key_id:          {{aws_access_key__primary}}
#            aws_secret_access_key:      {{aws_secret_key__primary}}
#            region_name:                {{aws_region__primary}}
#            BAT_VCAP_PASSWORD:          {{BAT_VCAP_PASSWORD}}
#            BAT_STEMCELL_NAME:          {{BAT_STEMCELL_NAME_hvm_ubuntu}}
#            stack_name:                 primary
#
#      - task: teardown-director
#        file: bosh-cpi-release/ci/tasks/teardown-director.yml

resources:
  - name: bosh-cpi-dev-artifacts
    type: s3
    source:
      regexp: bosh-aws-cpi\.tgz
      bucket: {{s3_aws_cpi_pipeline_bucket}}
      region_name: {{aws_region__primary}}
      access_key_id: {{aws_access_key__primary}}
      secret_access_key: {{aws_secret_key__primary}}

  - name: bosh-cpi-release-in
    type: git
    source:
      uri: git@github.com:cloudfoundry-incubator/bosh-aws-cpi-release.git
      branch: master
      private_key: {{github_deployment_key__bosh-aws-cpi-release}}
      ignore_paths:
        - .final_builds/**/*.yml
        - releases/**/*.yml

  - name: version-semver
    type: semver
    source:
      key:               current-version # dev-release version
      bucket:            {{s3_aws_cpi_pipeline_bucket}}
      access_key_id:     {{aws_access_key__primary}}
      secret_access_key: {{aws_secret_key__primary}}

  - name: bosh-init
    type: s3
    source:
      regexp: bosh-init-([0-9.]+)-linux-amd64
      bucket: {{s3_bosh_init_bucket}}
      region_name: {{aws_region__primary}}

  - name: bats
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-acceptance-tests.git
      branch: master

  - name: aws-ubuntu-hvm-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

  - name: bosh-src
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh.git
      branch: global-net-bats-test
